### ISSUE TITLE
Can you share your dataset analysis script for converting tfrecord dataset to .jpg file? 

### ISSUE THREAD

**Issue by HJ0Wang** [Abhishek-krg/covid-ir#1]
Thanks a lot for your dataset which is very useful to me. But  I want to convert the format of IR dataset that you kindly provide from the .record to .jpg. Could you share your script which could do this or anything else which could help me to analyse the .record dataset?

**Comment by Abhishek-krg** [comment]
The dataset is actually a derivative of FLIR's ADAS dataset and is for
detecting just the head and person entity in thermal images. FLIR already
provides Images in .jpg and .tiff thermal formats if you just want to
analyse them but if your work has something with head tracking I can
provide the dataset reader code also.

**Comment by HJ0Wang** [comment]
Thank you very much! I have downloaded the .jpg format from FLIR dataset according to your reply. The problem has been perfectly solved!

**Comment by Abhishek-krg** [comment]
Glad to hear that.
