### ISSUE TITLE
Backbone model

### ISSUE THREAD

**Issue by JTorres258** [Abhishek-krg/covid-ir#2]
Hello,

First of all, congrats for this repository. I would like to try the different pretrained weights you shared in this repository but with my own thermal data. I could not find the script where you define the backbone neural netwrok as you mention in the README.md file:

```python
efficientnet_base = efficientnet_model.EfficientNet.from_name(
        model_name=self._efficientnet_version,
        overrides={'rescale_input': False,'input_channels':1})
        
```

I would really appreciate if you could share it. I would also be very thankful if you could give me some tips about how to read the tfrecord files and how to prepare the model for inference. Thanks in advance.

**Comment by Abhishek-krg** [comment]
This repo uses tensorflow object detection library(you will find this code in the models folder of that repo), since it was based upon 3-channel RGB images only because of copyrights I cannot just change few lines and make it my own code for single channel thermal data so whatever changes I did make I have added them as small code-blocks here. Also make sure the image input pipline that you'll be building is compatible with your data sometimes thermal images are often represented as 16bit data and these piplines will generally have inputs as uint8.
Hope this helps.

**Comment by JTorres258** [comment]
Perfect ! Thank you so much for the information 😊

**Comment by JTorres258** [comment]
Hi again,

I am still having some problems to load the model. However, I was able to load the models downloaded from the [Object Detection API](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2_detection_zoo.md). In this case, they provide both ckpt and ckpt.index for restoring the checkpoint. I am not sure if this is the solution but, would you mind to upload these index files for each model (D0, D1 and D4)? Thanks in advance.

**Comment by Abhishek-krg** [comment]
As I said earlier the native tf-object detection models "code" are only compatible with 3-channel rgb images you'll have to manually change the code of model you need , to use just 1 channel from the models directory. In case of efficient-net models change the overrides parameters as shown in [/IR-thermal-head-detection-and-tracking/models/README.md](https://github.com/Abhishek-krg/IR-thermal-head-detection-and-tracking/blob/main/models/README.md) then you can load the model from this repos checkpoint

**Comment by JTorres258** [comment]
Hi,

Sorry, I think I didn't explain myself well. I followed the steps you mentioned with no problems, so the model is already compatible with 1-channel data. The thing is I found an error when trying to load the weights with the `ckpt-XX` file:

`NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./models/efficientdet_d0/ckpt-98`

After searching for this error, I found some people saying that the `ckpt-XX.index` file is also required for loading the weights. So my request is if you could inclue these files in the models you are sharing in this repository.

**Comment by Abhishek-krg** [comment]
I'm sorry I thought I had shared entire models config in zip files but clearly I forgot, I'll upload the index files also right in the models directory of this repo thank you for picking that out

**Comment by JTorres258** [comment]
Thank you so much !
